dshiksha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dshiksha_erp/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name="index"),
    # path('login', views.login_form, name="login"),
    path('Dashboard/AdminData', views.dashboard, name="dashboard"),

    path('',views.index,name='index'),
    
    path('accounts/login/', views.login_view, name="login_view"),
    path('accounts/logout', views.logout_form, name="logout"),
    path('accounts/login', views.login_view, name="login"),

    #admin
    path('Dashboard/AdminData', views.dashboard, name="dashboard"),
    # path('Dashboard/CreateSuperUser', views.create_superuser, name="create_superuser"),

    # settings
    path('Settings/AddState', views.add_state, name="add_state"),
    path('Settings/AddAcademicYear', views.add_academic_year, name="add_academic_year"),
    path('Settings/AddNationality', views.add_nationality, name="add_nationality"),
    path('Settings/AddMotherTongue', views.add_mother_tongue, name="add_mother_tomgue"),
    path('Settings/AddReligion', views.add_religion, name="add_religion"),
    path('Settings/AddPostOffice', views.add_post_office, name="add_post_office"),
    path('Settings/CreateArea', views.create_area, name="create_area"),
    #School
    path('School/CreateClass', views.add_class, name="add_class"),
    path('School/AssignClassLevel', views.school_assign_class_level, name="school_assign_class_level"),
    path('School/create_school', views.create_school, name="create_school"),
    path('School/CreateInstitutionLevel', views.create_institution_level, name="create_institution_level"),
    path('School/AddSchoolAffiliation', views.add_school_affiliation, name="add_school_affiliation"),
    
    
    #Staff
    path('Staff/AddStaffQualification', views.add_staff_qualification, name="add_staff_qualification"),
    path('Staff/AddDesignation', views.add_designation, name="add_subject"),

    #Fees
    path('Fees/CreateFeesType', views.create_fees_type, name="create_fees_type"),
    path('Fees/CreateSubFeesType', views.create_sub_fee_type, name="create_sub_fee_type"),
    path('Fees/CreateBank', views.create_bank, name="create_bank"),

    #Feedback
    path('Feedback/ReceiveFeedback',views.received_feedback,name="feedback_receive"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),


]

dshiksha_erp/models.py
from datetime import datetime
import os
from django.db import models
import uuid
from main.models import User


# Create your models here.
class AcademicYear(models.Model):
    AcademicYearID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    AcademicYear = models.CharField(max_length=50)
    IsActive = models.BooleanField()
    OrderID = models.IntegerField(unique=True)


class State(models.Model):
    StateID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    StateName = models.CharField(max_length=50)


class District(models.Model):
    DistrictID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    DistrictName = models.CharField(max_length=50)
    State = models.ForeignKey(State, on_delete=models.CASCADE)


class Taluk(models.Model):
    TalukID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    TalukName = models.CharField(max_length=50)
    District = models.ForeignKey(District, on_delete=models.CASCADE)


class Village(models.Model):
    VillageID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    VillageName = models.CharField(max_length=50)
    Taluk = models.ForeignKey(Taluk, on_delete=models.CASCADE)

class Area(models.Model):
    AreaID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    AreaType = models.CharField(max_length=100)

class Gender(models.Model):
    GenderID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    GenderName = models.CharField(max_length=50)
    GenderOrder = models.IntegerField(unique=True)


class Nationality(models.Model):
    NationalityID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    NationalityName = models.CharField(max_length=50)
    CountryCode = models.CharField(max_length=50)


class MotherTongue(models.Model):
    MotherTongueID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    MotherTongueName = models.CharField(max_length=50)


class BloodGroup(models.Model):
    BloodGroupID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    BloodGroupName = models.CharField(max_length=50)


class StaffQualification(models.Model):
    StaffQualificationID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    StaffQualificationName = models.CharField(max_length=50)

class Religion(models.Model):
    ReligionID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    ReligionName = models.CharField(max_length=50)

class CasteCategory(models.Model):
    CasteCategoryID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    CasteCategoryName = models.CharField(max_length=50)


class Caste(models.Model):
    CasteID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    CasteName = models.CharField(max_length=50)
    CasteCategory = models.ForeignKey(CasteCategory, on_delete=models.CASCADE)
    Religion = models.ForeignKey(Religion, on_delete=models.CASCADE)


class MaritalStatus(models.Model):
    MaritalStatusID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    MaritalStatus = models.CharField(max_length=50)


class Designation(models.Model):
    DesignationID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    DesignationName = models.CharField(max_length=50)


class PostOffice(models.Model):
    PostOfficeID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    PostOfficeName = models.CharField(max_length=50)
    Pincode = models.CharField(max_length=6)


class ClassLevel(models.Model):
    ClassLevelID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    ClassLevelName = models.CharField(max_length=50)
    ClassLevelCode = models.CharField(max_length=50)


class ClassList(models.Model):
    ClassID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    ClassName = models.CharField(max_length=50)
    OrderID = models.IntegerField()


class Section(models.Model):
    SectionID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    SectionName = models.CharField(max_length=50)


class StaffSubject(models.Model):
    StaffSubjectID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    StaffSubjectName = models.CharField(max_length=50)


class SchoolAffiliation(models.Model):
    SchoolAffiliationID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    SchoolAffiliation = models.CharField(max_length=50)


class ModeOfTransport(models.Model):
    ModeOfTransportID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    TransportName = models.CharField(max_length=50)
    OrderID = models.IntegerField()


class TransportData(models.Model):
    TransportDataID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    ModeOfTransport = models.ForeignKey(ModeOfTransport, on_delete=models.CASCADE)
    DriverName = models.CharField(max_length=50, null=True)
    DriverMobileNo = models.CharField(max_length=50, null=True)
    DriverEmail = models.EmailField(max_length=50, null=True)
    DriverAddress = models.TextField(null=True)


class NatureOfAppointment(models.Model):
    NatureOfAppointmentID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    NatureOfAppointment = models.CharField(max_length=100)


class SchoolType(models.Model):
    SchoolTypeID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    SchoolType = models.CharField(max_length=100)


class InstitutionLevel(models.Model):
    InstitutionLevelID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    InstitutionLevel = models.CharField(max_length=100)

class ModeOfPayment(models.Model):
    ModeOfPaymentID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    ModeOfPayment = models.CharField(max_length=50)
    OrderID = models.IntegerField()


class PaymentStatus(models.Model):
    PaymentStatusID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    PaymentStatus = models.CharField(max_length=50)

class FeesType(models.Model):
    FeesTypeID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    FeesTypeName = models.CharField(max_length=50)
    FeeTypeCode = models.CharField(max_length=50)


class Installment(models.Model):
    InstallmentID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    InstallmentName = models.CharField(max_length=50)
    OrderID=models.IntegerField()


class SubFee(models.Model):
    SubFeeID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    FeesType = models.ForeignKey(FeesType, on_delete=models.CASCADE)
    SubFeeName = models.CharField(max_length=50)

class ClassLevelFees(models.Model):
    ClassLevelFeesID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    ClassLevel = models.ForeignKey(ClassLevel, on_delete=models.CASCADE)
    FeesType = models.ForeignKey(FeesType, on_delete=models.CASCADE)

class Bank(models.Model):
    BankID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    BankName = models.CharField(max_length=50)
    OrderID = models.IntegerField()

class Online(models.Model):
    OnlineID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    OnlineAppName = models.CharField(max_length=50)
    OrderID = models.IntegerField()

# Feedback feature

def filepath_feedback(request,filename):
    old_file=filename
    timenow=datetime.now().strftime("%Y%m%d%H%M%S")
    filename=f'{timenow}_{old_file}'
    return os.path.join('uploads/feedback',filename)


class Feedback(models.Model):
    FeedbackID=models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    FeedbackData=models.TextField(max_length=500,null=True)
    FeedbackFile=models.FileField(upload_to=filepath_feedback,null=True)
    School=models.CharField(max_length=100)
    FeedbackDate = models.DateTimeField(auto_now=True)

dshiksha_erp/templates/dshiksha_erp/pages/Settings/add_academic_year.html
{% extends 'dshiksha_erp/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Add Academic Year
{% endblock title %}

{% block body %}

<div class="content">
    <div class="panel-header bg-primary-gradient">
        <div class="page-inner py-4">
            <div class="page-header  text-white">
                <h4 class="page-title  text-white">Assign Academic Year  </h4>
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="/">
                            <i class="flaticon-home  text-white fw-bold"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow  text-white fw-bold"></i>
                    </li>
                    <li class="nav-item">
                        <a href="/Settings/AddAcademicYear" class="text-white fw-bold">Assign Academic Year</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
    
    <div class="page-inner mt--5">
        {% if messages %}
            {% for message in messages %} 
            {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                <i class="bi-exclamation-octagon-fill"></i>
                <strong class="mx-2">Error!</strong> {{ message.message }}
            </div>
            {% endif %}
            {% if message.tags == 'info' %}
            <div class=" alert alert-success alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                <i class="bi-exclamation-octagon-fill"></i>
                <strong class="mx-2">Success!</strong> {{ message.message }}
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-rounded">
                    <div class="card-header">
                        <div class="card-title">Add Academic Year </div>
                    </div>

                    <div class="card-body">
                        <form action="/Settings/AddAcademicYear" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="form-type" value="add-academic-year">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="" class="form-label"> Academic Year </label>
                                        {{ academic_year_form.AcademicYear | attr:"class=form-control" }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="" class="form-label"> Order ID </label>
                                        {{ academic_year_form.OrderID | attr:"class=form-control" | attr:"type=number" | attr:"readonly" }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="exampleInputUsername1">&nbsp;</label>

                                        <div class="input-group col-xs-12">                                                        
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-primary"> Create </button>
                                            </span>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-header">
                        <div class="card-title">Academic Year List</div>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="10%">Sr.No.</th>
                                        <th>Order ID  </th>
                                        <th>Academic Year </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% if academic_year_list %}
                                    {% for ay in academic_year_list %}
                                    <tr>
                                        <td>  {{ forloop.counter }}  </td>
                                        <td> {{ ay.OrderID }}  </td>
                                        <td>                                                           
                                            <div>
                                                {{ ay.AcademicYear }} - {{ ay.OrderID }}
                                            </div>
                                        </td>                                                       
                                    </tr>
                                    {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

{% endblock body %}

{% block javascripts %}
    <script>
        
    setTimeout(function () {
        $('#alert').alert('close');
    }, 2500);

    </script>
{% endblock javascripts %}

dshiksha_erp/templates/dshiksha_erp/pages/Settings/add_state.html
{% extends 'dshiksha_erp/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %} Add State {% endblock title %}

{% block body %}
<div class="content">
    <div class="panel-header bg-primary-gradient">
        <div class="page-inner py-4">
            <div class="page-header text-white">
                <h4 class="page-title text-white">Add State,District,Taluk,Village  </h4>
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="/">
                            <i class="flaticon-home text-white fw-bold"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow text-white fw-bold"></i>
                    </li>
                    <li class="nav-item">
                        <a href="/Settings/AddState" class="text-white fw-bold">Add State</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
    
    <div class="page-inner mt--5">
        {% if messages %}
            {% for message in messages %} 
            {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                <i class="bi-exclamation-octagon-fill"></i>
                <strong class="mx-2">Error!</strong> {{ message.message }}
            </div>
            {% endif %}
            {% if message.tags == 'info' %}
            <div class=" alert alert-success alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                <i class="bi-exclamation-octagon-fill"></i>
                <strong class="mx-2">Success!</strong> {{ message.message }}
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-lg-3 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-body">
                        <div class="row">
                            <form action="/Settings/AddState" method="post" name="add-state-form">
                                    {% csrf_token %}
                                <input type="hidden" name="form-type" value="add-state">
                                <div class="form-group">
                                    <label for="" class="form-label"> State </label>
                                        {{ state_form.StateName | attr:"class=form-control" }}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary"> Create  </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-body">
                        <div class="row">
                            <form action="/Settings/AddState" method="post"
                                name="add-state-form">
                                {% csrf_token %}
                                <input type="hidden" name="form-type" value="add-district">
                                <div class="form-group">
                                    <label for="" class="form-label"> State </label>
                                    <select name="State" id="id_State" class="form-control">
                                        <option value=""> ---------- </option>
                                        {% if state_list %}
                                        {% for state in state_list %}
                                        <option value="{{ state.StateID }}"> 
                                            {{ state.StateName }} 
                                        </option>
                                        {% endfor %}
                                        {% endif %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="" class="form-label"> District </label>
                                    {{ district_form.DistrictName | attr:"class=form-control" }}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary"> Create
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>           
            </div>
            <div class="col-lg-3 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-body">
                        <div class="row">
                            <form action="/Settings/AddState" method="post"
                                name="add-state-form">
                                {% csrf_token %}
                                <input type="hidden" name="form-type" value="add-taluk">
                                <div class="form-group">
                                    <label for="" class="form-label"> District </label>
                                    <select name="DistrictName" id="id_DistrictName"
                                        class="form-control">
                                        <option value=""> ---------- </option>
                                        {% if district_list %}
                                        {% for district in district_list %}
                                        <option value="{{ district.DistrictID }}"> 
                                            {{ district.DistrictName }} </option>
                                        {% endfor %}
                                        {% endif %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="" class="form-label"> Taluk </label>
                                    {{ taluk_form.TalukName | attr:"class=form-control" }}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary"> Create
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>          
            </div>
            <div class="col-lg-3 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-body">
                        <div class="row">
                            <form action="/Settings/AddState" method="post"
                                name="add-state-form">
                                {% csrf_token %}
                                <input type="hidden" name="form-type" value="add-village">
                                <div class="form-group">
                                    <label for="" class="form-label"> Taluk </label>
                                    <select name="TalukName" id="id_TalukName"
                                        class="form-control">
                                        <option value=""> ---------- </option>
                                        {% if taluk_list %}
                                        {% for taluk in taluk_list %}
                                        <option value="{{ taluk.TalukID }}">
                                                {{ taluk.TalukName   }} </option>
                                        {% endfor %}
                                        {% endif %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="" class="form-label"> Village </label>
                                    {{ village_form.VillageName | attr:"class=form-control" }}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary"> Create
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex flex-column">
                <div class="card card-rounded">
                    <div class="card-header">
                        <div class="card-title">Location Details</div>
                    </div>
                    <div class="card-body"> 
                        <div class="table-responsive  mt-1">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="10%">Sr.No.</th>
                                        <th>State</th>
                                        <th>District</th>
                                        <th>Taluks</th>
                                        <th>Villages</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for state in state_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>
                                            {% if state_list %}
                                            {% for state in state_list %}
                                            <div>
                                                    {{ state.StateName }} 
                                            </div>
                                            {% endfor %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if district_list %}
                                            {% for district in district_list %}
                                            <div>
                                                {{ district.DistrictName }}</div>
                                            {% endfor %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if taluk_list %}
                                            {% for taluk in taluk_list %}
                                            <div>
                                                {{ taluk.TalukName }}
                                            </div>
                                            {% endfor %}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if village_list %}
                                            {% for village in village_list %}
                                            <div>
                                                {{ village.VillageName }}
                                                    - {{ village.Taluk.TalukName }}</div>
                                            {% endfor %}
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                    
            </div>
        </div>
      
    </div>
</div>
{% endblock body %}

{% block javascripts %}
    <script>
        
    setTimeout(function () {
        $('#alert').alert('close');
    }, 2500);

    </script>
{% endblock javascripts %}