dshiksha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),


]

school/urls.py
from django.urls import include, path
from . import views
from . import update_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name="index"),
    path("accounts/login/", views.login_view, name="login"),
    path('accounts/logout', views.logout_view, name='logout'),

    path('Dashboard', views.dashboard, name="school_dashboard"),


    # School Paths
    path('School/SchoolInfo', views.school_info, name="school_school_info"),
    path('School/AssignClass', views.assign_class, name="school_assign_class"),

    # Application
    path('Application/AssignApplicationFees', views.assign_application_fees, name="school_assign_application_fees"),
    path('Application/NewApplication', views.student_application, name="school_student_application"),
    path('Application/NewApplicationShow/<str:application_ID>', views.application_info_show,name="school_application_info_show"),

    # Admission
    path('Admission/NewAdmission', views.student_admission, name="school_student_admission"),

    #student
    path('Student/StudentShow/<str:student_id>', views.student_info_show, name="school_student_info_show"),

    # Attendance
    path('Attendance/MarkAttendance', views.mark_attendance, name="student_mark_attendance"),
    path('Attendance/ReportAttendance', views.attendance_list, name="student_attendance_info"),
    path('Attendance/StudentAttendanceShow/<str:student_id>', views.student_attendance_show, name="student_attendance_info"),


    # Staff Paths
    path('Staff/CreateStaff', views.create_staff, name="school_create_staff"),
    path('Staff/StaffInfo', views.staff_info, name="school_staff_info"),
    path('Staff/StaffInfoShow/<str:staff_ID>', views.staff_info_show, name="school_staff_info_show"),
    
    # Fees
    path('Fees/AssignFeeAmount', views.assign_fee_amount, name="assign_fee_amount"),
    path('Fees/CollectFee', views.collect_fee, name="collect_fee"),
    path('Fees/StudnetCollectFee/<str:student_id>', views.collect_fee_student, name="collect_fee_student"),
    path('Fees/ShowCollectFee/<str:student_id>', views.fee_info_show,name="fee_info_show"),

    # Print Reciept
    path('PrintFees/<str:student_id>', views.fees_reciept_pdf,name="fee_reciept"),


    #update the information
    path('Update/UpdateSchoolInfo/<str:school_id>',update_views.update_school,name="update_school_info"),
    path('Update/UpdateStaffInfo/<str:staff_id>',update_views.update_staff,name="update_staff_info"),
    path('Update/UpdateStudentInfo/<str:student_id>',update_views.update_student,name="update_student_info"),

    #Delete the information
    path('DeleteStaffInfo/<str:staff_id>',views.delete_staff,name="delete_staff_info"),
    path('DeleteStudentInfo/<str:student_id>',views.delete_student,name="delete_student_info"),

    #Feedback from school
    path('Feedback/FeedbackInfo',views.feedback_info,name="feedback_info"),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

school/models.py
from re import T
from datetime import datetime
import os
from django.db import models
import uuid
from dshiksha_erp import models as erp
from main.models import User

#upload file to static/uploads
def filepath_school(request,filename):
    old_file=filename
    timenow=datetime.now().strftime("%Y%m%d%H%M%S")
    # filename=f'{School.SchoolName}_{timenow}_{old_file}'
    filename=f'{timenow}_{old_file}'
    return os.path.join('uploads/school',filename)

def filepath_staff(request,filename):
    old_file=filename
    timenow=datetime.now().strftime("%Y%m%d%H%M%S")
    filename=f'{timenow}_{old_file}'
    # filename=f'{Staff.StaffName}_{timenow}_{old_file}'
    return os.path.join('uploads/staff',filename)
    
def filepath_student(request,filename):
    old_file=filename
    timenow=datetime.now().strftime("%Y%m%d%H%M%S")
    filename=f'{timenow}_{old_file}'
    # filename=f'{Students.StudentName}_{timenow}_{old_file}'
    return os.path.join('uploads/student',filename)

# Create your models here.
class Class(models.Model):
    ClassID = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    ClassList = models.ForeignKey(erp.ClassList, on_delete=models.CASCADE)
    ClassLevel = models.ForeignKey(erp.ClassLevel, on_delete=models.CASCADE)


class School(models.Model):
    SchoolID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    SchoolName = models.CharField(max_length=100)
    SchoolLogo = models.ImageField(upload_to=filepath_school,null=True)
    SchoolSeal = models.ImageField(upload_to=filepath_school,null=True)
    SchoolSign = models.ImageField(upload_to=filepath_school,null=True)
    Pincode = models.ForeignKey(erp.PostOffice, on_delete=models.CASCADE)
    SchoolDISECode = models.CharField(max_length=11)
    SchoolType = models.CharField(max_length=100)
    Area = models.ForeignKey(erp.Area, on_delete=models.CASCADE, null=True)
    InsitutionLevel = models.ForeignKey(erp.InstitutionLevel, on_delete=models.CASCADE, null=True)
    Landline = models.CharField(max_length=10)
    Mobile = models.CharField(max_length=10)
    Email = models.EmailField(max_length=100)
    Website = models.CharField(max_length=100)
    EstDate = models.DateField(null=True)
    History = models.TextField(max_length=5000)
    Village = models.ForeignKey(erp.Village, on_delete=models.CASCADE)
    SchoolCode = models.CharField(max_length=8)
    SchoolUsername = models.CharField(max_length=50)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    CurrentAcademicYear = models.ForeignKey(erp.AcademicYear, on_delete=models.CASCADE)
    SyllabusType = models.CharField(max_length=100)

    AccountantName = models.CharField(max_length=100)
    AccountantEmail = models.EmailField(max_length=100)
    AccountantMobile = models.CharField(max_length=10)
    AccountantWhatsAppNo = models.CharField(max_length=10)

    CorrespondentName = models.CharField(max_length=100)
    CorrespondentEmail = models.EmailField(max_length=100)
    CorrespondentMobile = models.CharField(max_length=10)
    CorrespondentWhatsAppNo = models.CharField(max_length=10)


class Staff(models.Model):
    StaffID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    SchoolID = models.ForeignKey(School, on_delete=models.CASCADE)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    StaffName = models.CharField(max_length=100)
    StaffEmailID = models.EmailField(max_length=100)
    StaffMobile = models.CharField(max_length=10)
    StaffPhoto = models.ImageField(upload_to=filepath_staff,null=True)
    Gender = models.ForeignKey(erp.Gender, on_delete=models.CASCADE, null=True)
    DOB = models.DateField(null=True)
    BloodGroup = models.ForeignKey(erp.BloodGroup, on_delete=models.CASCADE, null=True)
    MaritalStatus = models.ForeignKey(erp.MaritalStatus, on_delete=models.CASCADE, null=True)
    Caste = models.ForeignKey(erp.Caste, on_delete=models.CASCADE, null=True)
    MotherTongue = models.ForeignKey(erp.MotherTongue, on_delete=models.CASCADE, null=True)
    AddressLine1 = models.CharField(max_length=100)
    AddressLine2 = models.CharField(max_length=100)
    Village = models.ForeignKey(erp.Village, on_delete=models.CASCADE, null=True)
    Pincode = models.ForeignKey(erp.PostOffice, on_delete=models.CASCADE, null=True)
    StaffWhatsAppNo = models.CharField(max_length=10)
    # StaffWorkPost = models.CharField(max_length=100)
    Designation = models.ForeignKey(erp.Designation, on_delete=models.CASCADE, null=True)
    StaffQualification = models.ForeignKey(erp.StaffQualification, on_delete=models.CASCADE, null=True)
    Subject1 = models.ForeignKey(erp.StaffSubject, on_delete=models.CASCADE, related_name='Subject1', null=True)
    Subject2 = models.ForeignKey(erp.StaffSubject, on_delete=models.CASCADE, related_name='Subject2', null=True)
    DateOfAppointment = models.DateField(null=True)
    DateOfRetirement = models.DateField(null=True)
    StaffNo = models.CharField(max_length=50)
    AcademicYear = models.ForeignKey(erp.AcademicYear, on_delete=models.CASCADE, null=True)


class SCHOOLHead(models.Model):
    SCHOOLHeadID = models.UUIDField(default=uuid.uuid4, primary_key=True)
    School = models.ForeignKey(School, on_delete=models.CASCADE)
    Staff = models.ForeignKey(Staff, on_delete=models.CASCADE)


class AssignClass(models.Model):
    AssignClassID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    Class = models.ForeignKey(Class, on_delete=models.CASCADE)
    Section = models.ForeignKey(erp.Section, on_delete=models.CASCADE)
    School = models.ForeignKey(School, on_delete=models.CASCADE)
    AcademicYear = models.ForeignKey(erp.AcademicYear, on_delete=models.CASCADE)


class Subject(models.Model):
    SubjectID = models.UUIDField(
        primary_key=True, editable=False, default=uuid.uuid4)
    SubjectName = models.CharField(max_length=50)
    AssignClass = models.ForeignKey(AssignClass, on_delete=models.CASCADE)



class ApplicationNo(models.Model):
    ApplicationNoID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    Class = models.ForeignKey(Class, on_delete=models.CASCADE)
    School = models.ForeignKey(School, on_delete=models.CASCADE)
    Amount = models.FloatField()
    AcademicYear = models.ForeignKey(erp.AcademicYear, on_delete=models.CASCADE)
    ApplicationNo = models.IntegerField()


class Application(models.Model):
    ApplicationID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    ApplicationNo = models.CharField(max_length=100)
    StudentName = models.CharField(max_length=100)
    StudentDOB = models.DateField()
    Gender = models.ForeignKey(erp.Gender, on_delete=models.CASCADE, null=True)
    StudentMobileNo = models.CharField(max_length=10)
    ParentName = models.CharField(max_length=100)
    ParentMobileNo = models.CharField(max_length=10)
    Class = models.ForeignKey(Class, on_delete=models.CASCADE)
    SchoolID = models.ForeignKey(School, on_delete=models.CASCADE)
    ApplicationDate = models.DateField()
    Amount = models.FloatField()
    ModeOfPayment = models.ForeignKey(erp.ModeOfPayment, on_delete=models.CASCADE)
    #PaymentStatus = models.ForeignKey(erp.PaymentStatus, on_delete=models.CASCADE)


class Students(models.Model):
    AdmissionID = models.UUIDField(primary_key=True, default=uuid.uuid4)
    AdmissionNo = models.CharField(max_length=100)
    AdmissionDate = models.DateField()
    SchoolID = models.ForeignKey(School, on_delete=models.CASCADE)
    Class = models.ForeignKey(Class, on_delete=models.CASCADE)
    AssignedClass = models.ForeignKey(AssignClass, on_delete=models.CASCADE,null=True)
    Application = models.ForeignKey(Application, on_delete=models.CASCADE,null=True)
    AcademicYear = models.ForeignKey(erp.AcademicYear, on_delete=models.CASCADE, null=True)

    # student info
    StudentName = models.CharField(max_length=100)
    StudentDOB = models.DateField()
    Gender = models.ForeignKey(erp.Gender, on_delete=models.CASCADE, null=True)
    StudentMobileNo = models.CharField(max_length=10)
    Nationality = models.ForeignKey(erp.Nationality, on_delete=models.CASCADE, null=True)
    BloodGroup = models.ForeignKey(erp.BloodGroup, on_delete=models.CASCADE, null=True)
    Religion = models.ForeignKey(erp.Religion, on_delete=models.CASCADE, null=True)
    CasteCategory = models.ForeignKey(erp.CasteCategory, on_delete=models.CASCADE, null=True)
    Caste = models.ForeignKey(erp.Caste, on_delete=models.CASCADE, null=True)
    MotherTongue = models.ForeignKey(erp.MotherTongue, on_delete=models.CASCADE, null=True)
    StudentPhoto = models.ImageField(upload_to=filepath_student,null=True)
    PreviousSchoolName = models.CharField(max_length=100,null=True,blank=True)

    # Address info
    AddressLine1 = models.CharField(max_length=100)
    AddressLine2 = models.CharField(max_length=100)
    Village = models.ForeignKey(erp.Village, on_delete=models.CASCADE, null=True)
    Pincode = models.ForeignKey(erp.PostOffice, on_delete=models.CASCADE, null=True)

    # father info
    FatherName = models.CharField(max_length=100,null=True,blank=True)
    FatherMobileNo = models.CharField(max_length=10,null=True,blank=True)
    FatherWhatsappNo = models.CharField(max_length=10,null=True,blank=True)
    FatherEmail = models.EmailField(max_length=100,null=True,blank=True)
    FatherQualification = models.CharField(max_length=100,null=True,blank=True)
    FatherOccupation = models.CharField(max_length=100,null=True,blank=True)
    FatherIncome = models.FloatField(null=True,blank=True)

    # Mother info
    MotherName = models.CharField(max_length=100,null=True,blank=True)
    MotherMobileNo = models.CharField(max_length=10,null=True,blank=True)
    MotherWhatsappNo = models.CharField(max_length=10,null=True,blank=True)
    MotherEmail = models.EmailField(max_length=100,null=True,blank=True)
    MotherQualification = models.CharField(max_length=100,null=True,blank=True)

school/templates/school/Pages/Attendance/attendance_student_list.html
{% extends 'school/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Students Attendance Info | {{ school_name }} {% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}


{% block body %}
<div class="content">
    <div class="panel-header bg-primary-gradient">
        <div class="page-inner py-4">
            <div class="page-header text-white">
                <h4 class="page-title text-white">Attendance Report</h4>
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="/">
                            <i class="flaticon-home text-white fw-bold"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow text-white fw-bold"></i>
                    </li>
                    <li class="nav-item">
                        <a href="/Attendance/ReportAttendance" class="text-white fw-bold">Class Attendance Report</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="page-inner mt--5">
        {% if messages %}
            <div>
                {% for message in messages %} 
                {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                    <i class="bi-exclamation-octagon-fill"></i>
                    <strong class="mx-2">Error!</strong> {{ message.message }}
                    </div>
                {% endif %}
                {% if message.tags == 'info' %}
                <div class=" alert alert-success alert-dismissible d-flex align-items-center fade show my-1" id="alert">
                    <i class="bi-exclamation-octagon-fill"></i>
                    <strong class="mx-2">Success!</strong> {{ message.message }}
                    </div>
                {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Student Attendance According to Class</div>
                    </div>
                    <div class="card-body"> 
                        <div class="row">     
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="mb-3">
                                        <form action="/Attendance/ReportAttendance" method="post">
                                            {% csrf_token %}
                                            <label for="id_AssignClassID" class="form-label">Select Class</label>
                                            <select name="class_selected" id="id_AssignClassID" class="form-control">
                                                <option value=""> ----------- </option>
                                                {% for ac in assignclass_list %}
                                                    <option value="{{ ac.AssignClassID }}">{{ac.Class.ClassList.ClassName}}-{{ac.Section.SectionName}}</option>
                                                {% endfor %}
                                            </select>
                                            <div class="mt-3">
                                                <button type="submit" class="btn btn-primary">Show</button>
                                            </div>    
                                        </form>
                                    </div>
                                </div>                                                                       
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% if student_data %}
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card card-rounded">
                    <div class="card-header">
                       
                        <div class="row justify-content-center">
                            <div class="col-sm-4 col-md-4  fw-bold">
                                Class:<label class="form-check-label">{{class_section_data.Class.ClassList.ClassName}}</label>
                            </div>
                            <div class="col-sm-4 col-md-4  fw-bold">
                                Section:<label class="form-check-label">{{class_section_data.Section.SectionName}}</label>
                            </div>
                            <div class="col-sm-4 col-md-2  fw-bold">
                                Total Students:  <label>{{total_students}}</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="StudentData" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Sr.No.</th>
                                        <th>Student Name</th>
                                        <th>Gender</th>
                                        <th>StudentMobileNo</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in student_data %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>
                                            <div>
                                                {{ student.StudentName }} 
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                {{ student.Gender.GenderName }}
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                {{ student.StudentMobileNo }} 
                                            </div>
                                        </td>
                                        
                                        <td>
                                            <div>
                                                <a name="" id="" class="btn btn-info p-2 px-3" href="/Attendance/StudentAttendanceShow/{{ student.AdmissionID }}" role="button" data-toggle="tooltip" data-placement="top" title="View">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-12  grid-margin stretch-card">
                <div class="card card-rounded">
                    <div class="card-body">
                        <h1>Please select a class with student data</h1>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock body %}

{% block javascripts %}
<script src="/static/assets/js/setting-demo2.js"></script>
	<script >
        $(document).ready(function() {
            $('#StudentData').DataTable({
            });
        });


        setTimeout(function () {
            // Closing the alert
            $('#alert').alert('close');
        }, 2500);
    </script >

{% endblock javascripts %}